name: Deploy UniApp H5 to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - CONTRIBUTING.md

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置 Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建 UniApp H5
        run: pnpm build:h5

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署目标分支
          folder: dist/build/h5 # 构建输出目录
          clean: true # 自动清理旧文件
          clean-exclude: '' # 不保留额外文件
          force: false # 是否强推，一般 false 即可
          single-commit: true # 减少 commit 历史，让分支更干净
          commit-message: 自动部署 # 自定义 commit message
          token: ${{ secrets.GITHUB_TOKEN }}
